### PR TITLE
Nullable collections

### PR DESCRIPTION
**Pull request by HeikoTheissen**
Added checks:
* `Property` and `Term` with `Type="Collection(...)"` must specify `Nullable` in 4.01.
* `ReturnType Type="Collection(Edm.EntityType)"` must not specify `Nullable`.

### CODE REVIEW

**Review by ralfhandl — APPROVED** [review]

**Comment by HeikoTheissen** [comment]
Must we increase the version in package.json, and deploy it to npm?

**Comment by HeikoTheissen** [comment]
Must we update the [dependency](https://github.com/oasis-tcs/odata-vocabularies/blob/fae3463fa27656ede9718cd30cfa8ae58797ef28/package.json#L21)? If yes, please deploy to npm.

**Review by ralfhandl — APPROVED** [review]
I'll publish the NPM package once you have merged the PR

**Comment by ralfhandl** [comment]
Published new NPM package: https://www.npmjs.com/package/odata-csdl

**Pull request merged**
