### PR TITLE
XSD version 1.1

### PR DESCRIPTION
**Pull request by HeikoTheissen**

### CODE REVIEW

**Review by ralfhandl — CHANGES_REQUESTED** [review]
We need an automated test first, and this test needs to work unchanged for the "old" XSDs, so better have a different pull request for the automated tests that is merged first.

**Comment by HeikoTheissen** [comment]
Closed because of missing XSD 1.1 support.

**Comment by HeikoTheissen** [comment]
Are the JARs necessary?

**Comment by HeikoTheissen** [comment]
They are.

**Comment by ralfhandl** [comment]
Are the JARs only necessary for XSD 1.1? 

The validator seems to work without addtional JARs on my machine with the XSD 1.0 schemas.

**Pull request closed without merging**
